# Generated by Django 4.0.6 on 2022-08-26 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('address', models.TextField(max_length=500, verbose_name='Address')),
                ('contactno', models.IntegerField(default=0, verbose_name='Contact No.')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('profilepic', models.ImageField(upload_to='clientimg', verbose_name='Profile Photo')),
                ('active', models.IntegerField(default=0, verbose_name='Active')),
                ('areaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.area', verbose_name='Area')),
                ('cityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.city', verbose_name='City')),
            ],
        ),
    ]
