# Generated by Django 3.1.1 on 2022-09-01 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_auto_20220901_1059'),
        ('giftkeepers', '0002_product_giftkeepers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Giftkeeper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('address', models.CharField(max_length=500, verbose_name='Address')),
                ('contactNo', models.IntegerField(blank=True, default=0, null=True, verbose_name='Contact')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('areaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.area', verbose_name='Area')),
                ('cityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.city', verbose_name='City')),
            ],
        ),
        migrations.RemoveField(
            model_name='giftkeepers',
            name='areaId',
        ),
        migrations.RemoveField(
            model_name='giftkeepers',
            name='cityId',
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='ClientRegistration',
        ),
        migrations.DeleteModel(
            name='Giftkeepers',
        ),
    ]
