# Generated by Django 3.1.1 on 2022-09-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftkeepers', '0003_auto_20220901_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftkeeper',
            name='contactNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Contact'),
        ),
    ]
