# Generated by Django 4.0.6 on 2022-09-08 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftkeepers', '0005_product_price_alter_giftkeeper_id_alter_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftkeeper',
            name='profilePic',
            field=models.ImageField(null=True, upload_to='profileimg', verbose_name='Image'),
        ),
    ]
