# Generated by Django 4.0.6 on 2022-09-08 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giftkeepers', '0006_giftkeeper_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='giftKeeperId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='giftkeepers.giftkeeper'),
        ),
    ]
