# Generated by Django 3.1.1 on 2022-11-23 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftkeepers', '0007_product_giftkeeperid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftkeeper',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
