# Generated by Django 4.0.6 on 2022-11-24 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_alter_area_id_alter_city_id_alter_employee_id'),
        ('giftkeepers', '0009_alter_giftkeeper_id_alter_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customertbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('address', models.CharField(max_length=500, verbose_name='Address')),
                ('contactNo', models.IntegerField(blank=True, null=True, verbose_name='Contact')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('areaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.area', verbose_name='Area')),
                ('cityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.city', verbose_name='City')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invno', models.CharField(blank=True, max_length=500, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('totalprice', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('customerid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='giftkeepers.customertbl')),
                ('giftkeeperid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='giftkeepers.giftkeeper')),
                ('productid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='giftkeepers.product')),
            ],
        ),
    ]
