# Generated by Django 4.0.6 on 2022-11-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftkeepers', '0010_customertbl_customerorders'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorders',
            name='totalcost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
