# Generated by Django 4.0.6 on 2022-12-01 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giftkeepers', '0011_customerorders_totalcost'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('landmark', models.CharField(blank=True, max_length=1000, null=True)),
                ('pmode', models.CharField(blank=True, max_length=100, null=True)),
                ('invno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='giftkeepers.customerorders')),
            ],
        ),
    ]
