# Generated by Django 4.0.6 on 2022-12-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftkeepers', '0012_checkoutorders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutorders',
            name='invno',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
