# Generated by Django 4.0.6 on 2022-12-08 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftkeepers', '0013_alter_checkoutorders_invno'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorders',
            name='active',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
