# Generated by Django 3.1.1 on 2022-12-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftkeepers', '0015_auto_20221210_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorders',
            name='empid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
