# Generated by Django 4.0.6 on 2022-12-19 17:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('giftkeepers', '0017_alter_checkoutorders_id_alter_customerorders_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorders',
            name='currentdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
