# Generated by Django 4.0.6 on 2022-12-19 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftkeepers', '0018_customerorders_currentdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorders',
            name='currentdate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
