# Generated by Django 4.0.6 on 2022-08-29 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='contactNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Contact'),
        ),
    ]
