# Generated by Django 5.1.5 on 2025-01-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_alter_area_id_alter_city_id_alter_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admintbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='Username')),
                ('password', models.CharField(max_length=200, verbose_name='Passwords')),
            ],
        ),
    ]
